### PR TITLE
Make HttpServer a case object

### PR DESCRIPTION
**Pull request by dryajov**
Fixes - https://github.com/status-im/nim-libp2p/pull/593

### CODE REVIEW

**Review by Menduist — CHANGES_REQUESTED** [review]
I find this code a bit weird, it's mixing OOP & compile time constructs instead of sticking to just one?

You should either make a single case object and don't extend it, or leave it as before and just replace the
`when server is TlsHttpServer:`
with either a runtime if, or create a `createStream` (or `init` or whatever) method which is extended by the `TlsHttpServer`, no?

EDIT: and in both cases, `proc accept*(server: HttpServer | TlsHttpServer)` shouldn't happen, you should just have `proc accept*(server: HttpServer)`

**Review by Menduist — APPROVED** [review]
:+1:

**Comment by dryajov** [comment]
You're right, `HttpServer` shouldn't be extended and `TlsHttpServer` should just be an alias. `accept` is also probably fine taking `HttpServer`. 

The idea behind separating the two has always been more semantic convenience than anything else, it should be clear from calling `TlsHttpServer.create()` that you're creating a Tls server and vice versa.

**Comment by dryajov** [comment]
good catch btw 👍

**Pull request merged**
